version: '3.8'

services:
  gwan-site:
    image: node:20-alpine
    container_name: gwan-site
    working_dir: /app
    command: pm2-runtime ecosystem.config.js
    volumes:
      - ./ecosystem.config.js:/app/ecosystem.config.js
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gwan-site.rule=Host(`gwan.com.br`)"
      - "traefik.http.routers.gwan-site.entrypoints=websecure"
      - "traefik.http.routers.gwan-site.tls.certresolver=letsencrypt"
      - "traefik.http.services.gwan-site.loadbalancer.server.port=3000"
    networks:
      - gwan

networks:
  gwan:
    external: true
