version: '3.8'

services:
  gwan-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gwan-site
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gwan-site.rule=Host(`gwan.com.br`)"
      - "traefik.http.routers.gwan-site.entrypoints=websecure"
      - "traefik.http.routers.gwan-site.tls.certresolver=letsencrypt"
      - "traefik.http.services.gwan-site.loadbalancer.server.port=3000"
    restart: always
    networks:
      - gwan

networks:
  gwan:
    external: true
