version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres           # Altere para seu usuário
      POSTGRES_PASSWORD: minha_senha_segura # Altere para uma senha forte
      POSTGRES_DB: chatwoot_production                # Altere para o nome do banco desejado
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - gwan  # Alterado para rede gwan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatwoot_production"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /data/postgres
      o: bind

networks:
  gwan:
    external: true
