services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gwan_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pazdeDeus2025
    networks:
      - gwan
    ports:
      - "5672:5672"     # Porta AMQP para conexões de aplicativos
      - "15672:15672"   # Porta HTTP para acessar o painel (já liberada via Traefik também)
    command: ["rabbitmq-server", "--log-level", "info"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.gwan.com.br`)"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.routers.rabbitmq.tls.certresolver=letsencrypt"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
networks:
  gwan:
    external: true  # Rede deve existir previamente no Docker