version: '3.8'

services:
  gwan-site:
    image: node:20-bullseye
    container_name: gwan-site
    working_dir: /app
    command: sh -c "npm install -g serve && serve -s build -l 3000"
    volumes:
      - /opt/gwan-site:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gwan-site.rule=Host(`gwan.com.br`)"
      - "traefik.http.routers.gwan-site.entrypoints=websecure"
      - "traefik.http.routers.gwan-site.tls.certresolver=letsencrypt"
      - "traefik.http.services.gwan-site.loadbalancer.server.port=3000"
    restart: always
    networks:
      - gwan

networks:
  gwan:
    external: true
